name: Setup
description: Common setup for Node + pnpm

runs:
  using: "composite"
  steps:  
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i
        shell: bash