/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main/route'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as MainPlacesImport } from './routes/_main/places'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as MainPlacesIdImport } from './routes/_main/places.$id'

// Create/Update Routes

const MainRouteRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)

const MainPlacesRoute = MainPlacesImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => MainRouteRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)

const MainPlacesIdRoute = MainPlacesIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MainPlacesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthRouteImport
    }
    '/_main/places': {
      id: '/_main/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof MainPlacesImport
      parentRoute: typeof MainRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainRouteImport
    }
    '/_main/places/$id': {
      id: '/_main/places/$id'
      path: '/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof MainPlacesIdImport
      parentRoute: typeof MainPlacesImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainPlacesRouteChildren {
  MainPlacesIdRoute: typeof MainPlacesIdRoute
}

const MainPlacesRouteChildren: MainPlacesRouteChildren = {
  MainPlacesIdRoute: MainPlacesIdRoute,
}

const MainPlacesRouteWithChildren = MainPlacesRoute._addFileChildren(
  MainPlacesRouteChildren,
)

interface MainRouteRouteChildren {
  MainPlacesRoute: typeof MainPlacesRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainPlacesRoute: MainPlacesRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof MainRouteRouteWithChildren
  '/register': typeof AuthRegisterRoute
  '/places': typeof MainPlacesRouteWithChildren
  '/': typeof MainIndexRoute
  '/places/$id': typeof MainPlacesIdRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteRouteWithChildren
  '/register': typeof AuthRegisterRoute
  '/places': typeof MainPlacesRouteWithChildren
  '/': typeof MainIndexRoute
  '/places/$id': typeof MainPlacesIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_auth/register': typeof AuthRegisterRoute
  '/_main/places': typeof MainPlacesRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/places/$id': typeof MainPlacesIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/register' | '/places' | '/' | '/places/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/register' | '/places' | '/' | '/places/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/register'
    | '/_main/places'
    | '/_main/'
    | '/_main/places/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_main"
      ]
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/register"
      ]
    },
    "/_main": {
      "filePath": "_main/route.tsx",
      "children": [
        "/_main/places",
        "/_main/"
      ]
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_main/places": {
      "filePath": "_main/places.tsx",
      "parent": "/_main",
      "children": [
        "/_main/places/$id"
      ]
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/_main/places/$id": {
      "filePath": "_main/places.$id.tsx",
      "parent": "/_main/places"
    }
  }
}
ROUTE_MANIFEST_END */
