name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./setup.yml
        
      - name: Run unit tests
        run: pnpm run test:unit

  integration:
    name: Integration tests  
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./setup.yml

      - name: Run integration tests
        run: pnpm run test:integration